In [44]:
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [45]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))



In [46]:
train_df.head()

Unnamed: 0   index  loan_amnt  int_rate  installment home_ownership  \
0       57107   57107    13375.0    0.1797       483.34       MORTGAGE   
1      141451  141451    21000.0    0.1308       478.68       MORTGAGE   
2      321143  321143    20000.0    0.1240       448.95       MORTGAGE   
3       11778   11778     3000.0    0.1240       100.22           RENT   
4      169382  169382    30000.0    0.1612      1056.49       MORTGAGE   

   annual_inc verification_status loan_status pymnt_plan  ...  pct_tl_nvr_dlq  \
0    223000.0        Not Verified    low_risk          n  ...           100.0   
1    123000.0     Source Verified    low_risk          n  ...            85.0   
2    197000.0     Source Verified    low_risk          n  ...            85.7   
3     45000.0        Not Verified    low_risk          n  ...           100.0   
4    133000.0     Source Verified    low_risk          n  ...           100.0   

   percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  tot_hi_cred_lim  \
0              50.0                   0.0        0.0         577150.0   
1              33.3                   0.0        0.0         132750.0   
2              33.3                   0.0        0.0         628160.0   
3              16.7                   1.0        0.0          42006.0   
4              66.7                   0.0        0.0         283248.0   

   total_bal_ex_mort  total_bc_limit total_il_high_credit_limit  \
0           122018.0         32000.0                   170200.0   
1            27896.0         15900.0                    35398.0   
2           114043.0         22600.0                    90340.0   
3            20761.0         19900.0                    15406.0   
4           109056.0         79500.0                    58778.0   

   hardship_flag  debt_settlement_flag  
0              N                     N  
1              N                     N  
2              N                     N  
3              N                     N  
4              N                     N  

[5 rows x 86 columns]

In [47]:
# Convert categorical data to numeric and separate target feature for training data
y_train = train_df["loan_status"]
X_train = train_df.drop(columns = ["loan_status"])
X_train.head()

Unnamed: 0   index  loan_amnt  int_rate  installment home_ownership  \
0       57107   57107    13375.0    0.1797       483.34       MORTGAGE   
1      141451  141451    21000.0    0.1308       478.68       MORTGAGE   
2      321143  321143    20000.0    0.1240       448.95       MORTGAGE   
3       11778   11778     3000.0    0.1240       100.22           RENT   
4      169382  169382    30000.0    0.1612      1056.49       MORTGAGE   

   annual_inc verification_status pymnt_plan    dti  ...  pct_tl_nvr_dlq  \
0    223000.0        Not Verified          n  29.99  ...           100.0   
1    123000.0     Source Verified          n  11.26  ...            85.0   
2    197000.0     Source Verified          n  11.28  ...            85.7   
3     45000.0        Not Verified          n  18.08  ...           100.0   
4    133000.0     Source Verified          n  27.77  ...           100.0   

   percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  tot_hi_cred_lim  \
0              50.0                   0.0        0.0         577150.0   
1              33.3                   0.0        0.0         132750.0   
2              33.3                   0.0        0.0         628160.0   
3              16.7                   1.0        0.0          42006.0   
4              66.7                   0.0        0.0         283248.0   

   total_bal_ex_mort total_bc_limit  total_il_high_credit_limit  \
0           122018.0        32000.0                    170200.0   
1            27896.0        15900.0                     35398.0   
2           114043.0        22600.0                     90340.0   
3            20761.0        19900.0                     15406.0   
4           109056.0        79500.0                     58778.0   

   hardship_flag  debt_settlement_flag  
0              N                     N  
1              N                     N  
2              N                     N  
3              N                     N  
4              N                     N  

[5 rows x 85 columns]

In [48]:
# Convert categorical data to numeric and separate target feature for testing data
y_test = test_df["loan_status"]
X_test = test_df.drop(columns = ["loan_status"])
X_test.head()

Unnamed: 0  index  loan_amnt  int_rate  installment home_ownership  \
0       67991  67991    40000.0    0.0819       814.70       MORTGAGE   
1       25429  25429     6000.0    0.1524       208.70           RENT   
2       38496  38496     3600.0    0.1695       128.27           RENT   
3       19667  19667    20000.0    0.1524       478.33           RENT   
4       37505  37505     3600.0    0.1240       120.27           RENT   

   annual_inc verification_status pymnt_plan    dti  ...  pct_tl_nvr_dlq  \
0    140000.0        Not Verified          n  19.75  ...            97.7   
1     55000.0        Not Verified          n  11.52  ...            66.7   
2     42000.0        Not Verified          n   6.74  ...           100.0   
3    100000.0        Not Verified          n  12.13  ...           100.0   
4     50000.0        Not Verified          n  16.08  ...           100.0   

   percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  tot_hi_cred_lim  \
0               0.0                   0.0        0.0         527975.0   
1               0.0                   0.0        0.0          34628.0   
2               0.0                   0.0        0.0          23100.0   
3              50.0                   0.0        0.0          56481.0   
4              25.0                   0.0        0.0          45977.0   

   total_bal_ex_mort total_bc_limit  total_il_high_credit_limit  \
0            70914.0        74600.0                     99475.0   
1            23460.0         5900.0                     23628.0   
2            19183.0         7300.0                     15000.0   
3            43817.0        13800.0                     35981.0   
4            32448.0        21000.0                     24977.0   

   hardship_flag  debt_settlement_flag  
0              N                     N  
1              N                     N  
2              N                     N  
3              N                     N  
4              N                     N  

[5 rows x 85 columns]

In [49]:
X_dummies_train = pd.get_dummies(X_train)
X_dummies_test = pd.get_dummies(X_test)
print(f"Train: {X_dummies_train.shape}, Test: {X_dummies_test.shape}")

Train: (12180, 94), Test: (4702, 93)


In [50]:
y_label_train = LabelEncoder().fit_transform(train_df['loan_status'])
y_label_train

y_label_test = LabelEncoder().fit_transform(test_df['loan_status'])
y_label_test

array([1, 1, 1, ..., 0, 0, 0])

In [51]:
# add missing dummy variables to testing set
for col in X_dummies_train.columns:
    if col not in X_dummies_test.columns:
        X_dummies_test[col]=0

In [52]:
print(f"Train: {X_dummies_train.shape}, Test: {X_dummies_test.shape}")


Train: (12180, 94), Test: (4702, 94)


In [53]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
clf_logistic  = LogisticRegression(solver='lbfgs').fit(X_dummies_train, y_label_train) 

print(f"Training Data Score: {clf_logistic.score(X_dummies_train, y_label_train)}")
print(f"Testing Data Score: {clf_logistic.score(X_dummies_test, y_label_test)}");

Training Data Score: 0.648440065681445
Testing Data Score: 0.5253083794130158


C:\Users\Stron\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [54]:
# Train a Random Forest Classifier model and print the model score
from sklearn.ensemble import RandomForestClassifier
clf_forest = RandomForestClassifier(random_state=42, n_estimators=200).fit(X_dummies_train, y_label_train)

print(f'Training Score: {clf_forest.score(X_dummies_train, y_label_train)}')
print(f'Testing Score: {clf_forest.score(X_dummies_test, y_label_test)}')

Training Score: 1.0
Testing Score: 0.623139089749043


In [55]:
# Scale the data
scaler = StandardScaler().fit(X_dummies_train)
X_train_scaled = scaler.transform(X_dummies_train)
X_test_scaled = scaler.transform(X_dummies_test)

In [56]:
# Train the Logistic Regression model on the scaled data and print the model score
clf_lr = LogisticRegression().fit(X_train_scaled, y_label_train)


print(f'Training Score: {clf_lr.score(X_train_scaled, y_label_train)}')
print(f'Testing Score: {clf_lr.score(X_test_scaled, y_label_test)}')

Training Score: 0.713136288998358
Testing Score: 0.7201190982560612


C:\Users\Stron\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [57]:
# Train a Random Forest Classifier model on the scaled data and print the model score
clf_rf = RandomForestClassifier(random_state=42, n_estimators=500).fit(X_train_scaled, y_label_train)

print(f'Training Score: {clf_forest.score(X_dummies_train, y_label_train)}')
print(f'Testing Score: {clf_forest.score(X_dummies_test, y_label_test)}')

Training Score: 1.0
Testing Score: 0.623139089749043


In [58]:
# Conf. Matrix for Better visual of results for models
from sklearn.metrics import confusion_matrix , classification_report
y_true = y_label_test
y_pred = clf_lr.predict(X_test_scaled)
confusion_matrix(y_true, y_pred)

array([[1242, 1109],
       [ 207, 2144]], dtype=int64)

In [59]:
# Reshape
matrix = confusion_matrix(y_true, y_pred)
matrix = matrix.astype('float') / matrix.sum(axis=1)[:, np.newaxis]

In [60]:
# Classification Report LR Model

target_names = ['low risk', 'high risk']
print(classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

    low risk       0.86      0.53      0.65      2351
   high risk       0.66      0.91      0.77      2351

    accuracy                           0.72      4702
   macro avg       0.76      0.72      0.71      4702
weighted avg       0.76      0.72      0.71      4702



In [61]:
# Conf Matrix for RFC Model
y_true1 = y_label_test
y_pred1 = clf_rf.predict(X_test_scaled)
confusion_matrix(y_true1, y_pred1)

array([[ 767, 1584],
       [ 226, 2125]], dtype=int64)

In [62]:
# Reshape
matrix = confusion_matrix(y_true1, y_pred1)
matrix = matrix.astype('float') / matrix.sum(axis=1)[:, np.newaxis]

In [63]:
#Classification Report RFC Model
print(classification_report(y_true1, y_pred1, target_names=target_names))

              precision    recall  f1-score   support

    low risk       0.77      0.33      0.46      2351
   high risk       0.57      0.90      0.70      2351

    accuracy                           0.62      4702
   macro avg       0.67      0.62      0.58      4702
weighted avg       0.67      0.62      0.58      4702



<!--LR Model Unscaled Data scores: Training Data Score: 0.648440065681445
                                   Testing Data Score: 0.5253083794130158 -->
    
<!--RFC Model Unscaled Data scores:  Training Score: 1.0
                                     Testing Score: 0.623139089749043  -->
                          
<!--LR Model scaled Data scores:    Training Score: 0.713136288998358
                                    Testing Score: 0.7201190982560612  -->
                                   
<!--RFC Model scaled Data scores:   Training Score: 1.0
                                    Testing Score: 0.623139089749043   -->
                          
<!--RFC model seems to train and test the same even in scaled and unscaled.
     Regrerssion Model performs a more accurate model when scaled-->
     
<!--OverView using a confusion matrix to better understand the models and test and training scores seems to show an improvement from .52 to .72 from unscaled to scaled. The simple model produced slight better results from what was shown.-->
                          


The results from looking at the scores and confusion matrix of both models seems to produce better scores on the LR model than the RFC model.  Seems the simple model showed you don't always need complexity and the less is more approach can work out results to a better accuracy. The RFC model on scaled and unscaled gave similar results but still the closer gap between trained and tested was more consistant and showed greater improvement of the LR models.